### ISSUE TITLE
Can't use decimal types in MongoDB

### ISSUE THREAD

**Issue by evandrogiovanini** [quasar-analytics/quasar#2167]
Can't use a MongoDB collection that has decimals in it. Using MongoDB 3.4.4 and Quasar 16.1.6.

Example:

Import the following CSV file:
```
"car.total_value.decimal()","car.name.string()"
"1.50","Example"
```

Imported with:
`mongoimport -h 127.0.0.1  --db dectest --collection col --type csv --headerline --columnsHaveTypes --file dectest.csv`

The following is returned in Mongo Shell:
```
> db.col.findOne()
{
	"_id" : ObjectId("59105c6c476de35edb9f452c"),
	"car" : {
		"total_value" : NumberDecimal("1.50"),
		"name" : "Example"
	}
}
```

From Quasar REPL, I get the following exception:

```
💪 $ select * from col
💪 $ Exception in thread "AeshProcess: 12" java.lang.RuntimeException: Detected unknown BSON type "\x13" for fieldname "total_value". Are you using the latest driver version?
	at quasar.effect.Failure$.quasar$effect$Failure$$$anonfun$16(Failure.scala:125)
	at quasar.effect.Failure$$anon$5.apply(Failure.scala:105)
	at quasar.effect.Failure$$anon$5.apply(Failure.scala:103)
	at scalaz.NaturalTransformation$$anon$2.apply(NaturalTransformation.scala:19)
	at scalaz.NaturalTransformations$$anonfun$natToFunction$1.apply(NaturalTransformation.scala:41)
	at scalaz.$bslash$div.fold(Either.scala:57)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at scalaz.NaturalTransformation$$anon$2.apply(NaturalTransformation.scala:19)
	at scalaz.NaturalTransformations$$anonfun$natToFunction$1.apply(NaturalTransformation.scala:41)
	at scalaz.$bslash$div.fold(Either.scala:58)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at scalaz.NaturalTransformations$$anonfun$natToFunction$1.apply(NaturalTransformation.scala:41)
	at scalaz.$bslash$div.fold(Either.scala:58)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at scalaz.Free.foldMap(Free.scala:217)
	at scalaz.Free.foldMap(Free.scala:219)
	at scalaz.Free$$anonfun$foldMap$2.apply(Free.scala:219)
	at scalaz.EitherT$$anonfun$flatMap$1$$anonfun$apply$4.apply(EitherT.scala:93)
	at scalaz.$bslash$div.fold(Either.scala:58)
	at scalaz.EitherT$$anonfun$flatMap$1.apply(EitherT.scala:93)
	at scalaz.EitherT$$anonfun$flatMap$1.apply(EitherT.scala:93)
	at scalaz.Free$$anonfun$step$1.apply(Free.scala:200)
	at scalaz.Free$$anonfun$step$1.apply(Free.scala:200)
	at scalaz.Free.step(Free.scala:202)
	at scalaz.Free.foldMap(Free.scala:215)
	at scalaz.Free$$anonfun$foldMap$2.apply(Free.scala:219)
	at scalaz.Kleisli$$anonfun$flatMap$1$$anonfun$apply$1.apply(Kleisli.scala:51)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$.Try(Task.scala:457)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:33)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
	at scalaz.concurrent.Future.step(Future.scala:118)
	at scalaz.concurrent.Future.unsafePerformListen(Future.scala:75)
	at scalaz.concurrent.Future.unsafePerformAsync(Future.scala:159)
	at scalaz.concurrent.Future.unsafePerformSync(Future.scala:184)
	at scalaz.concurrent.Task.unsafePerformSync(Task.scala:99)
	at quasar.repl.Main$$anon$1.execute(Main.scala:81)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sellout** [comment]
Quasar doesn’t yet support any MongoDb 3.4 features yet. This is part of the larger issue, #1954.

**Comment by sellout** [comment]
We should also be handling this error better – it says it’s a RuntimeException, but I’m guessing that’s created by us after catching the actual MongoDB error.

**Comment by sellout** [comment]
So, two steps to fix this:

1. ensure that unhandled MongoDB types don’t blow up the query; then
2. update the Mongo driver and handle large decimal values correctly.

**Comment by rintcius** [comment]
Just upgrading the Mongo driver (without doing anything else) will result in a conflict with Spark, since Spark requires Netty 4.0 whereas Mongo driver > 3.3 requires 4.1, see https://github.com/quasar-analytics/quasar/blob/1d1ff661138117964fc6d8fade54d094edc47030/project/Dependencies.scala#L67-L81

To get the newest Mongo driver working, I'm thinking to give shading a shot.
I saw that an [earlier attempt was reverted](https://github.com/quasar-analytics/quasar/commit/0eb6a4a291fba4fea4ead7ec92663ea984c7e141), but since shading [has been fixed in latest Netty 4.1.14 and 4.0.50](https://github.com/netty/netty/pull/6995) it may actually work this time. However this is under the assumption that this was the bug in Netty that prevented Spark and new Mongo driver to work together.

@jedesah and @rabbitonweb do you remember if this was indeed the problem? Were there any other problems with the shaded implementation?

**Comment by jedesah** [comment]
I don't remember too many specifics but I will say that shading is extremely immature in the Java ecosystem and in particular for Scala. If you have experience (especially positive) with it, then, by all means, give it a try because I had none. I personally would be reluctant to give it a try again myself.

This will become a non-issue once we support dynamic loading of connectors. Java 9 and project Jigsaw also offer promising solutions, but I wouldn't wait on that stuff to materialize.

**Comment by rintcius** [comment]
Yeah, I really would like to be able to avoid it, but don't see any other way to get Spark and new Mongo working together.
