### ISSUE TITLE
Couchbase visualization query behaves erratically

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#2229]
SlamData 4.2.0
Quasar 16.1.5
Couchbase 

Works properly on MongoDB, MarkLogic and Spark connectors.

Reproduction inside of SlamData:

* Click on `patients` or `smallpatients` dataset
* Notice the preview table
* advance one card, select Setup Chart
* Select Bar Chart
* Configure chart:
  * Category: state
  * Measure 1: age  (average, not sum)
  * Parallel: gender
* Advance one card, select Show Chart
* Notice there is no separation by gender, shown below:

<img width="423" alt="bar-cb" src="https://cloud.githubusercontent.com/assets/7375598/26264162/1191db72-3c99-11e7-843d-39e0b04ff20b.png">

The SQL² query generated is:

```
SELECT AVG(age) AS measure, state AS category, null AS stack, gender AS parallel FROM `/couchbase/patients-bucket/smallpatients` GROUP BY gender, state ORDER BY gender ASC, state ASC
```

Oftentimes the first time you run through this process the visualization will appear, but will be missing gender info (see screenshot above).  But navigating back to the chart config card, changing something (like removing and re-adding `gender` as Parallel) and navigating back will often produce a 500 error in the UI:

```
An error occurred.
Error compiling query: An unknown error ocurred: 500 ""
```

Which I'm assuming is related to this JVM exception in the log file:
```
17/05/19 15:59:28 ERROR Stage: Error running route: Request(method=GET, uri=/compile/fs/couchbase/patients-bucket/?q=SELECT%20SUM%28age%29%20AS%20measure%2C%20state%20AS%20category%2C%20null%20AS%20stack%2C%20gender%20AS%20parallel%20FROM%20%60/couchbase/patients-bucket/patients%60%20GROUP%20BY%20gender%2C%20state%20ORDER%20BY%20gender%20ASC%2C%20state%20ASC, headers=Headers(Host: localhost:20223, Connection: keep-alive, User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36, Accept: */*, Referer: http://localhost:20223/slamdata/workspace.html, Accept-Encoding: gzip, deflate, sdch, br, Accept-Language: en-US,en;q=0.8, Cookie: _ga=GA1.1.1929231136.1489598833; ajs_anonymous_id=%22a885cbe1-a96b-4796-9bc4-f905fac96a65%22; _cio=4f38de6d-1623-1f66-fd46-17069bf334cc; ajs_user_id=null; ajs_group_id=null; __hstc=181257784.1aee4225412be9edfa24c003ec1774b4.1493396270135.1495222368679.1495229517835.33; __hssrc=1; __hssc=181257784.2.1495229517835; hubspotutk=1aee4225412be9edfa24c003ec1774b4)
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at scala.StringContext.standardInterpolator(StringContext.scala:126)
	at scala.StringContext.s(StringContext.scala:95)
	at quasar.physical.couchbase.RenderQuery$.quasar$physical$couchbase$RenderQuery$$$anonfun$4(RenderQuery.scala:116)
	at quasar.physical.couchbase.RenderQuery$$$Lambda$2055/331714893.apply(Unknown Source)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at scalaz.DisjunctionInstances1$$anon$1.bind(Either.scala:452)
	at scalaz.DisjunctionInstances1$$anon$1.bind(Either.scala:439)
	at scalaz.syntax.BindOps.$greater$greater$eq(BindSyntax.scala:11)
	at matryoshka.Recursive$class.matryoshka$Recursive$class$$$anonfun$2(Recursive.scala:40)
	at matryoshka.Recursive$class$lambda$$cataM$1.apply(Recursive.scala:40)
	at matryoshka.package$.hylo(package.scala:225)
	at matryoshka.package$.matryoshka$package$$$anonfun$17(package.scala:225)
	at matryoshka.package$lambda$$hylo$1.apply(package.scala:225)
	at scala.collection.immutable.List.map(List.scala:273)
	at scalaz.std.ListInstances$$anon$1.map(List.scala:32)
	at scalaz.std.ListInstances$$anon$1.map(List.scala:14)
	at scalaz.IdInstances$$anon$1.traverse(Id.scala:53)
	at scalaz.syntax.TraverseOps.traverse(TraverseSyntax.scala:14)
	at quasar.physical.couchbase.N1QLTraverseInstance$$anon$1.traverseImpl(N1QLTraverseInstance.scala:35)
	at quasar.physical.couchbase.N1QLTraverseInstance$$anon$1.traverseImpl(N1QLTraverseInstance.scala:24)
	at scalaz.Traverse$Traversal.run(Traverse.scala:50)
	at scalaz.Traverse$class.map(Traverse.scala:112)
	at quasar.physical.couchbase.N1QLTraverseInstance$$anon$1.map(N1QLTraverseInstance.scala:24)
	at scalaz.syntax.FunctorOps.$u2218(FunctorSyntax.scala:14)
	at matryoshka.package$.hylo(package.scala:225)
	at matryoshka.package$.matryoshka$package$$$anonfun$17(package.scala:225)
	at matryoshka.package$lambda$$hylo$1.apply(package.scala:225)
```

This happens with both the `patients` and `smallpatients` datasets, the latter of which is only 10 documents.

Expected visualization should be like this:

<img width="417" alt="bar-mongo" src="https://cloud.githubusercontent.com/assets/7375598/26264172/1a81d17e-3c99-11e7-8b2b-621e56c69d41.png">

Fictitious `smallpatients` dataset attached:

[smallpatients.txt](https://github.com/slamdata/slamdata/files/1015690/smallpatients.txt)

(Closed SlamData [1810](https://github.com/slamdata/slamdata/issues/1810) and reopened here)

**Comment by zeeiyerWork** [comment]
As discussed - assigning ASAP milestone, since it would be good to demo this at Couchbase conference.
