### ISSUE TITLE
Couchbase Area visualization is not showing series data

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#2230]
SlamData 4.2.0
Quasar 16.1.5
Couchbase

Works properly on MongoDB, MarkLogic and Spark connectors.

Reproduction inside of SlamData:

* Click on `timeseries` or `smalltimeseries` dataset
* Notice the preview table
* Advance one card
* Select Setup Chart
* Select Area Chart
* Configure chart:
  * Dimension: `dt` 
  * Measure 1: `value`
  * Series: `sensor`
  * Stacked: checked
  * Smooth: checked
* Advance one card, select Show Chart

The SQL² generated was:
```
SELECT SUM(value) AS measure, dt AS dimension, sensor AS series FROM `/couchbase/timeseries-bucket/smalltimeseries` GROUP BY sensor, dt ORDER BY sensor ASC, dt ASC
```

This is similar to Quasar Issue #2229, in fact it may be identical but the behavior is slightly different.

In this instance I was unable to get a chart at all, and after ~20 minutes was provided a `500` error without a description.  RAM usage for Quasar/SlamData went as high as 4GB and CPU reached 50% of system capacity (2 of 4 cores) before an OutOfMemoryError occurred:

```
17/05/19 17:16:24 ERROR Stage: Error running route: Request(method=GET, uri=/compile/fs/couchbase/timeseries-bucket/?q=SELECT%20SUM%28value%29%20AS%20measure%2C%20dt%20AS%20dimension%2C%20sensor%20AS%20series%20FROM%20%60/couchbase/timeseries-bucket/smalltimeseries%60%20GROUP%20BY%20sensor%2C%20dt%20ORDER%20BY%20sensor%20ASC%2C%20dt%20ASC, headers=Headers(Host: localhost:20223, Connection: keep-alive, User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36, Accept: */*, Referer: http://localhost:20223/slamdata/workspace.html, Accept-Encoding: gzip, deflate, sdch, br, Accept-Language: en-US,en;q=0.8, Cookie: _ga=GA1.1.1929231136.1489598833; ajs_anonymous_id=%22a885cbe1-a96b-4796-9bc4-f905fac96a65%22; _cio=c8ae88fa-b7a4-59fe-38b6-0fb2f7d72cf0; ajs_user_id=null; ajs_group_id=null; __hstc=181257784.1aee4225412be9edfa24c003ec1774b4.1493396270135.1495229517835.1495232571656.34; __hssrc=1; __hssc=181257784.20.1495232571656; hubspotutk=1aee4225412be9edfa24c003ec1774b4)
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at scala.StringContext.standardInterpolator(StringContext.scala:126)
	at scala.StringContext.s(StringContext.scala:95)
	at quasar.physical.couchbase.RenderQuery$.quasar$physical$couchbase$RenderQuery$$$anonfun$4(RenderQuery.scala:116)
	at quasar.physical.couchbase.RenderQuery$$$Lambda$2389/1857246992.apply(Unknown Source)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at scalaz.DisjunctionInstances1$$anon$1.bind(Either.scala:452)
	at scalaz.DisjunctionInstances1$$anon$1.bind(Either.scala:439)
	at scalaz.syntax.BindOps.$greater$greater$eq(BindSyntax.scala:11)
	at matryoshka.Recursive$class.matryoshka$Recursive$class$$$anonfun$2(Recursive.scala:40)
	at matryoshka.Recursive$class$lambda$$cataM$1.apply(Recursive.scala:40)
	at matryoshka.package$.hylo(package.scala:225)
	at matryoshka.package$.matryoshka$package$$$anonfun$17(package.scala:225)
	at matryoshka.package$lambda$$hylo$1.apply(package.scala:225)
	at scala.collection.immutable.List.map(List.scala:273)
	at scalaz.std.ListInstances$$anon$1.map(List.scala:32)
	at scalaz.std.ListInstances$$anon$1.map(List.scala:14)
	at scalaz.IdInstances$$anon$1.traverse(Id.scala:53)
	at scalaz.syntax.TraverseOps.traverse(TraverseSyntax.scala:14)
	at quasar.physical.couchbase.N1QLTraverseInstance$$anon$1.traverseImpl(N1QLTraverseInstance.scala:35)
	at quasar.physical.couchbase.N1QLTraverseInstance$$anon$1.traverseImpl(N1QLTraverseInstance.scala:24)
	at scalaz.Traverse$Traversal.run(Traverse.scala:50)
	at scalaz.Traverse$class.map(Traverse.scala:112)
	at quasar.physical.couchbase.N1QLTraverseInstance$$anon$1.map(N1QLTraverseInstance.scala:24)
	at scalaz.syntax.FunctorOps.$u2218(FunctorSyntax.scala:14)
	at matryoshka.package$.hylo(package.scala:225)
	at matryoshka.package$.matryoshka$package$$$anonfun$17(package.scala:225)
	at matryoshka.package$lambda$$hylo$1.apply(package.scala:225)
```

The Couchbase server showed no noticeable spike in usage. I was also able to query Couchbase through the Couchbase Query console during this time, showing that Couchbase was responsive.

`smalltimeseries` dataset attached below:

[smalltimeseries.txt](https://github.com/quasar-analytics/quasar/files/1015713/smalltimeseries.txt)

**Comment by zeeiyerWork** [comment]
As discussed, dropping this in ASAP milestone.
