### ISSUE TITLE
[spark] Divide integration tests fail 

### ISSUE THREAD

**Issue by rintcius** [quasar-analytics/quasar#2269]
excerpt from https://travis-ci.org/quasar-analytics/quasar/jobs/238058859

```
[error] ! divide [./divide.test] (133 ms)
[error]  org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 242.0 failed 1 times, most recent failure: Lost task 1.0 in stage 242.0 (TID 430, localhost, executor driver): java.lang.ArithmeticException: Division by zero
[error]  	at java.math.BigDecimal.divide(BigDecimal.java:1742)
[error]  	at scala.math.BigDecimal.$div(BigDecimal.scala:571)
[error]  	at quasar.physical.sparkcore.fs.CoreMap$.divide(CoreMap.scala:376)
[error]  	at quasar.physical.sparkcore.fs.CoreMap$.quasar$physical$sparkcore$fs$CoreMap$$$anonfun$65(CoreMap.scala:233)
[error]  	at quasar.physical.sparkcore.fs.CoreMap$.quasar$physical$sparkcore$fs$CoreMap$$$anonfun$92(CoreMap.scala:304)
[error]  	at quasar.physical.sparkcore.fs.CoreMap$.quasar$physical$sparkcore$fs$CoreMap$$$anonfun$94(CoreMap.scala:313)
[error]  	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
[error]  	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
[error]  	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
[error]  	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
[error]  	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
[error]  	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
[error]  	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
[error]  	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
[error]  	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
[error]  	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
[error]  	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
[error]  	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
[error]  	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
[error]  	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
[error]  	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:935)
[error]  	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:935)
[error]  	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
[error]  	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
[error]  	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
[error]  	at org.apache.spark.scheduler.Task.run(Task.scala:99)
[error]  	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
[error]  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]  	at java.lang.Thread.run(Thread.java:745)
[error]  
[error]  Driver stacktrace: (DAGScheduler.scala:1435)
[error] org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
[error] org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
[error] org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
[error] org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
[error] org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
[error] org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
[error] org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
[error] org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
[error] org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
[error] org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
[error] org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
[error] org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
[error] org.apache.spark.SparkContext.runJob(SparkContext.scala:1918)
[error] org.apache.spark.SparkContext.runJob(SparkContext.scala:1931)
[error] org.apache.spark.SparkContext.runJob(SparkContext.scala:1944)
[error] org.apache.spark.SparkContext.runJob(SparkContext.scala:1958)
[error] org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:935)
[error] org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[error] org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[error] org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
[error] org.apache.spark.rdd.RDD.collect(RDD.scala:934)
[error] quasar.physical.sparkcore.fs.local.queryfile$.quasar$physical$sparkcore$fs$local$queryfile$$$anonfun$4(queryfile.scala:49)
[error] quasar.physical.sparkcore.fs.CoreMap$.divide(CoreMap.scala:376)
[error] quasar.physical.sparkcore.fs.CoreMap$.quasar$physical$sparkcore$fs$CoreMap$$$anonfun$65(CoreMap.scala:233)
[error] quasar.physical.sparkcore.fs.CoreMap$.quasar$physical$sparkcore$fs$CoreMap$$$anonfun$92(CoreMap.scala:304)
[error] quasar.physical.sparkcore.fs.CoreMap$.quasar$physical$sparkcore$fs$CoreMap$$$anonfun$94(CoreMap.scala:313)
[error] org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:935)
[error] org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:935)
[error] org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
[error] org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
[error] org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
[error] org.apache.spark.scheduler.Task.run(Task.scala:99)
[error] org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
[error] CAUSED BY
[error]  java.lang.ArithmeticException: Division by zero (CoreMap.scala:376)
[error] quasar.physical.sparkcore.fs.CoreMap$.divide(CoreMap.scala:376)
[error] quasar.physical.sparkcore.fs.CoreMap$.quasar$physical$sparkcore$fs$CoreMap$$$anonfun$65(CoreMap.scala:233)
[error] quasar.physical.sparkcore.fs.CoreMap$.quasar$physical$sparkcore$fs$CoreMap$$$anonfun$92(CoreMap.scala:304)
[error] quasar.physical.sparkcore.fs.CoreMap$.quasar$physical$sparkcore$fs$CoreMap$$$anonfun$94(CoreMap.scala:313)
[error] org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:935)
[error] org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:935)
[error] org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
[error] org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
[error] org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
[error] org.apache.spark.scheduler.Task.run(Task.scala:99)
[error] org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
```

**Comment by rintcius** [comment]
Also see @sellout 's note here https://github.com/quasar-analytics/quasar/pull/2256#issuecomment-305312647

**Comment by rabbitonweb** [comment]
Is that failing test is now in master or is it pending?

**Comment by rabbitonweb** [comment]
Ok, I see all, ignore previous comment. Added to July2017
