### ISSUE TITLE
Mounting a View with local bindings corrupts the metastore

### ISSUE THREAD

**Issue by natefaubion** [quasar-analytics/quasar#2294]
Creating a view with this:
```
foo := 42;
SELECT * FROM `/mongodb/data/olympics`
```

Corrupts the metastore, and it has to be nuked.

**Comment by natefaubion** [comment]
On 16.1.10, which is what slamdata uses.

**Comment by natefaubion** [comment]
```
17/06/07 14:25:36 ERROR Stage: Error running route: Request(method=GET, uri=/metadata/fs/, headers=Headers(Host: localhost:8080, Connection: keep-alive, Pragma: no-cache, Cache-Control: no-cache, User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36, Accept: */*, Referer: http://localhost:8080/files/index.html, Accept-Encoding: gzip, deflate, sdch, br, Accept-Language: en-US,en;q=0.8,it;q=0.6, Cookie: ajs_anonymous_id=%22b48bfb82-081e-4ed9-a399-add15e117b3a%22; _ga=GA1.1.589864032.1441299432; _drip_client_5059421=vid%253Dbc3731a03026013482b90e9dd67883c3%2526pageViews%253D584%2526sessionPageCount%253D8%2526lastVisitedAt%253D1472228267323%2526weeklySessionCount%253D8%2526lastSessionAt%253D1472227190854; ajs_user_id=null; ajs_group_id=null)
quasar.metastore.UnexpectedValueException
	at quasar.metastore.package$.unexpectedValue(package.scala:101)
	at quasar.metastore.package$.quasar$metastore$package$$$anonfun$25(package.scala:94)
	at quasar.metastore.package$$$Lambda$603/1436528264.apply(Unknown Source)
	at scalaz.$bslash$div.leftMap(Either.scala:98)
	at quasar.metastore.package$.quasar$metastore$package$$$anonfun$24(package.scala:94)
	at quasar.metastore.package$$$Lambda$101/1641565704.apply(Unknown Source)
	at doobie.util.composite$Composite$$anon$1$$anonfun$4.apply(composite.scala:45)
	at doobie.util.composite$Composite$$anon$1$$anonfun$4.apply(composite.scala:45)
	at doobie.util.composite$Composite$$anonfun$1$$anonfun$apply$3.apply(composite.scala:37)
	at doobie.util.composite$Composite$$anonfun$1$$anonfun$apply$3.apply(composite.scala:37)
	at doobie.free.resultset$ResultSetOp$$anonfun$primitive$1$$anonfun$apply$1.apply(resultset.scala:91)
	at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:339)
	at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:339)
	at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$7.apply(Task.scala:347)
	at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$7.apply(Task.scala:347)
	at scalaz.concurrent.Task$.Try(Task.scala:457)
	at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:347)
	at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:347)
	at scalaz.concurrent.Future.step(Future.scala:119)
	at scalaz.concurrent.Future.unsafePerformListen(Future.scala:75)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:99)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:99)
	at scalaz.Free.resume(Free.scala:117)
	at scalaz.Free.go2$1(Free.scala:161)
	at scalaz.Free.go(Free.scala:165)
	at scalaz.Free.run(Free.scala:271)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
