### ISSUE TITLE
UnshiftArray is unimplemented in Mimir

### ISSUE THREAD

**Issue by dugdun** [quasar-analytics/quasar#2855]
**Use case**: Pivot Tables

Quasar Version: 22.0.2 (I also get 500 error in 24.0.15, but nothing is written to the log file in that version, so we might have different log levels set up)

**Note**: Pivot Tables work just fine in new MongoDB, and based off error this appears to be specific to Mimir so writing the issue up against Quasar.

Error message in log file:

```
17/09/28 13:49:12 ERROR service-errors: Error servicing request: GET /invoke/fs/mimir/Demos/%E2%9C%97%20-%20Chained%20Markdown.slam/.tmp/out6d03d3b1-05db-4086-a959-c841b4a1c5c2/card6d03d3b105db4086a959c841b4a1c5c2 from 0:0:0:0:0:0:0:1
scala.NotImplementedError: unimplemented value of type (src.P.Library.Reduction, quasar.qscript.FreeMap[T]) at Mimir.scala:328
        at slamdata.Predef.$qmark$qmark$qmark(Predef.scala:104)
        at quasar.mimir.Mimir$$anonfun$planQScriptCore$lzycompute$1$1.quasar$mimir$Mimir$$anonfun$$extractReduction$1(Mimir.scala:328)
        at quasar.mimir.Mimir$$anonfun$planQScriptCore$lzycompute$1$1$$anonfun$11.apply(Mimir.scala:333)
        at quasar.mimir.Mimir$$anonfun$planQScriptCore$lzycompute$1$1$$anonfun$11.apply(Mimir.scala:333)
        at scala.collection.immutable.List.map(List.scala:273)
        at quasar.mimir.Mimir$$anonfun$planQScriptCore$lzycompute$1$1.apply(Mimir.scala:333)
        at quasar.mimir.Mimir$$anonfun$planQScriptCore$lzycompute$1$1.apply(Mimir.scala:272)
        at scalaz.$bslash$div.fold(Either.scala:57)
        at quasar.mimir.Mimir$$anonfun$planQST$lzycompute$1$1.apply(Mimir.scala:237)
        at quasar.mimir.Mimir$$anonfun$planQST$lzycompute$1$1.apply(Mimir.scala:237)
        at scalaz.$bslash$div.fold(Either.scala:58)
        at matryoshka.patterns.package$.matryoshka$patterns$package$$$anonfun$5(package.scala:59)
        at matryoshka.patterns.package$lambda$$ginterpretM$1.apply(package.scala:59)
        at matryoshka.patterns.package$lambda$$ginterpretM$1.apply(package.scala:59)
        at scalaz.EitherT$$anonfun$flatMap$1$$anonfun$apply$4.apply(EitherT.scala:93)
        at scalaz.$bslash$div.fold(Either.scala:58)
        at scalaz.EitherT$$anonfun$flatMap$1.apply(EitherT.scala:93)
        at scalaz.EitherT$$anonfun$flatMap$1.apply(EitherT.scala:93)
        at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
        at scalaz.WriterT$$anonfun$flatMapF$1.apply(WriterT.scala:62)
        at scalaz.WriterT$$anonfun$flatMapF$1.apply(WriterT.scala:61)
        at scalaz.Kleisli$$anonfun$flatMap$1$$anonfun$apply$1.apply(Kleisli.scala:51)
        at scalaz.Kleisli$$anonfun$flatMap$1$$anonfun$apply$1.apply(Kleisli.scala:51)
        at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
        at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
        at scalaz.concurrent.Task$.Try(Task.scala:457)
        at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:35)
        at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:33)
        at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
        at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
        at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
        at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
        at scalaz.concurrent.Future.step(Future.scala:118)
        at scalaz.concurrent.Future.unsafePerformListen(Future.scala:75)
        at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
        at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
        at scalaz.Free$$anonfun$map$1.apply(Free.scala:99)
        at scalaz.Free$$anonfun$map$1.apply(Free.scala:99)
        at scalaz.Free.resume(Free.scala:117)
        at scalaz.Free.go2$1(Free.scala:161)
        at scalaz.Free.go(Free.scala:165)
        at scalaz.Free.run(Free.scala:271)
        at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:428)
        at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:428)
        at delorean.package$FutureAPI$$anonfun$toTask$1$$anonfun$apply$3$$anonfun$apply$1.apply$mcV$sp(package.scala:31)
        at delorean.package$FutureAPI$$anonfun$toTask$1$$anonfun$apply$3$$anonfun$apply$1.apply(package.scala:31)
        at delorean.package$FutureAPI$$anonfun$toTask$1$$anonfun$apply$3$$anonfun$apply$1.apply(package.scala:31)
        at scalaz.concurrent.StrategysLow$$anon$3$$anon$4.call(Strategy.scala:77)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by djspiewak** [comment]
This is being caused by the fact that `UnshiftArray` and `UnshiftObject` are unimplemented in mimir (along with nearly every other connector).  @kRITZCREEK, do you need the `[foo...]` construct for pivot tables?  Like, is it fundamental?  If so, then we can bump up the priority of this implementation on the mimir side.  It's just a pain, and a very dangerous operation due to our columnar implementation.
